version: "3"

services:
  postgres:
    image: postgres:17
    container_name: finance-app-container
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: financeuser
      POSTGRES_DB: financeapp
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
